services:
    server:
        image: itzg/minecraft-server:java17-alpine
        environment:
            EULA: "TRUE"

            # INFO: Make sure to set the correct Minecraft version, modloader, and Git URL.
            VERSION: "1.20.1"
            TYPE: "FORGE"
            FORGE_VERSION: "47.3.7"
            PACKWIZ_URL: "https://raw.githubusercontent.com/exoumoon/server_template/main/pack.toml"

            MEMORY: "12G"
            USE_AIKAR_FLAGS: "true"
            ENABLE_AUTOPAUSE: "true"
            VIEW_DISTANCE: 12

            MODE: "survival"
            DIFFICULTY: "hard"
            MAX_PLAYERS: "4"
            ALLOW_FLIGHT: "true"

            MOTD: ""
            ICON: "https://raw.githubusercontent.com/exoumoon/server_template/main/assets/icon.png"

            ONLINE_MODE: "false"

            # RCON_CMDS_STARTUP: |-
            #     /team add New
            #     /team add Old

            # RCON_CMDS_ON_CONNECT: |-
            #     /team join New @a[team=]
            #     /clear @a[team=New]
            #     /team join Old @a[team=New]

            RCON_CMDS_FIRST_CONNECT: |-
                /whitelist on
                /whitelist add mxxntype
                /op mxxntype

        ports:
            - "25565:25565"
        volumes:
            - ./server:/data
